# Generated by Django 2.2.16 on 2022-04-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220408_0200'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_title',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='review',
            new_name='review_id',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title_id'),
        ),
    ]
