# Generated by Django 2.2.16 on 2022-04-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220402_1851'),
        ('reviews', '0003_auto_20220403_0029'),
    ]

    operations = [
    ]
