# Generated by Django 2.2.16 on 2022-04-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220408_0631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
