# Generated by Django 2.2.16 on 2022-04-03 17:20

import django.contrib.auth.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20220403_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.validate_username, django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
